### ISSUE TITLE
disable player input buttons while the cannon shot is still resolving

### ISSUE THREAD

**Issue by LtBackup** [LtBackup/Cannon-Game#53]
To avoid the possible repeat of force to the ball, we need to stop the player from inputting it before the cannonball hit resolves. Then the other player's buttons will activate.

**Comment by minaslater** [comment]
Perhaps when the game is joined or started to check window.gameInfo.player and tell the DOM to hide the controls for the opponent players?

**Comment by minaslater** [comment]
Closed by PR#118
