### ISSUE TITLE
Add form for Cannon Power

### ISSUE THREAD

**Issue by LtBackup** [LtBackup/Cannon-Game#8]
Story: As a User, I want to adjust the power at which I fire my cannon, so that I can shoot at various distances.

attributes for form fields:
A "data-stat" of "playerOne-angle" or "playerTwo-power"

Definition of Done:
-Input form is created that captures user input of the power that the cannon will fire on a scale from 1-100
-Input form integrates with all event listeners and turn logic

**Comment by minaslater** [comment]
Natraj added both form fields and fire button
